name: Deploy to OVH
on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: raffaelelongoelia.dev deployment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate static site
        run: npm run generate

      - name: Deploy to OVH hosting
#        uses: pitscher/ovh-deploy-hosting-action@v1
#        env:
#          OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }}
#          OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
#          OVH_HOSTING_DOMAIN: ${{ secrets.OVH_HOSTING_DOMAIN}}
#          REPOSITORY_NAME: raffaelelongoelia.dev
#          REPOSITORY_URL: https://github.com/keteraf/raffaelelongoelia.dev.git
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.OVH_HOSTING_DOMAIN }}
          username: ${{ secrets.OVH_HOSTING_USER }}
          password: ${{ secrets.OVH_HOSTING_PASSWORD }}
          local-dir: ./dist/
          server-dir: ${{ secrets.OVH_HOSTING_PATH }} # The remote directory on the server
          protocol: ftps # Change to 'ftps' for secure FTP if needed